  - job_name: json
    metrics_path: /probe
    params:
      module: [default]
    static_configs:
      - targets:
        - http://shinobi_host:8000/export_data.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
      ## Location of the json exporter's real <hostname>:<port>
        replacement: stat_host:7979

  - job_name: 'shinobi_exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['stat_host:9765']
      
  - job_name: 'nvidia_smi_exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['stat_host:9101']